### PR TITLE
Feature/strategy

### PR DESCRIPTION
**Pull request by mmichailidis**
*AFTER* observer 
It will also fix a minor bug in observer ( forgot to add a call in sloth )

### CODE REVIEW

**Comment by dranidis** [comment]
This branch has conflicts that must be resolved.

Conflicting files
src/main/java/com/asdt/farm/Animal.java
src/main/java/com/asdt/farm/App.java
src/main/java/com/asdt/farm/Dog.java
src/main/java/com/asdt/farm/Sloth.java

**Comment by mmichailidis** [comment]
strange.. one moment

**Comment by mmichailidis** [comment]
Ok both should be fixed

**Comment by dranidis** [comment]
We should try to improve the example since currently only the quantity of eaten food changes by a number. 

Actually the two strategies could be simply implemented with the AbstractEat strategy providing the multiplier at the constructor.

**Comment by mmichailidis** [comment]
Yes but this would limit the possibilities that can be followed up. Like different food and stuff

**Pull request merged**
